version: 1
disable_existing_loggers: False
formatters:
  verbose:
    format: "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
  simple:
    format: "%(levelname)s %(message)s"
handlers:
  file:
    level: DEBUG
    class: logging.FileHandler
    filename: debug.log
    mode: w
    formatter: verbose
loggers:
  jobs_scraper:
    handlers: [file]
    level: DEBUG
    propagate: False
root:
  level: WARNING
  handlers: [file]