version: 1
disable_existing_loggers: False
formatters:
  verbose:
    format: "%(asctime)s | %(name)-45s | %(levelname)-8s | %(message)s"
  simple:
    format: "%(levelname)-8s %(message)s"
  console:
    format: "%(name)-45s: %(levelname)-8s %(message)s"
handlers:
  file:
    level: DEBUG
    class: logging.FileHandler
    filename: "debug.log"
    mode: a
    formatter: verbose
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: console
loggers:
  generate_insights.run_data_analysis.file:
    level: DEBUG
    handlers: [file]
    propagate: False
  generate_insights.run_data_analysis.console:
    level: INFO
    handlers: [console]
    propagate: False
  data_analysis.job_data_analyzer.file:
    level: DEBUG
    handlers: [file]
    propagate: False
  data_analysis.job_data_analyzer.console:
    level: INFO
    handlers: [console]
    propagate: False
root:
  level: DEBUG
  handlers: [console]
  propagate: False