version: 1
disable_existing_loggers: False
formatters:
  verbose:
    format: "%(asctime)s | %(name)-12s | %(levelname)-8s | %(message)s"
  simple:
    format: "%(levelname)-8s %(message)s"
  console:
    format: "%(name)-12s: %(levelname)-8s %(message)s"
handlers:
  file:
    level: DEBUG
    class: logging.FileHandler
    filename: debug.log
    mode: w
    formatter: verbose
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: console
loggers:
  jobs_scraper.load_scraped_job_data.file:
    level: DEBUG
    handlers: [file]
    propagate: False
  jobs_scraper.load_scraped_job_data.console:
    level: INFO
    handlers: [console]
    propagate: False
root:
  level: DEBUG
  handlers: [console]